#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IOS_DIR="${ROOT_DIR}/ios"
PLIST_PATH="${IOS_DIR}/Resources/GoogleService-Info.plist"
XCCONFIG_PATH="${IOS_DIR}/Config/FirebaseSecrets.xcconfig"

mkdir -p "${IOS_DIR}/Config"

if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_BASE64:-}" ]]; then
  if ! printf "%s" "${GOOGLE_SERVICE_INFO_PLIST_BASE64}" | base64 --decode > "${PLIST_PATH}" 2>/dev/null; then
    printf "%s" "${GOOGLE_SERVICE_INFO_PLIST_BASE64}" | base64 -D > "${PLIST_PATH}"
  fi
fi

if [[ -f "${PLIST_PATH}" ]]; then
  REVERSED_CLIENT_ID=$(/usr/libexec/PlistBuddy -c "Print REVERSED_CLIENT_ID" "${PLIST_PATH}")
  if [[ "${REVERSED_CLIENT_ID}" == *"REPLACE"* ]] || [[ "${REVERSED_CLIENT_ID}" != com.googleusercontent.apps.* ]]; then
    echo "ERROR: GoogleService-Info.plist has invalid REVERSED_CLIENT_ID: ${REVERSED_CLIENT_ID}"
    echo "Use a real plist from Firebase Console, or set GOOGLE_SERVICE_INFO_PLIST_BASE64 in Codemagic."
    exit 1
  fi
  {
    echo "// Generated by ios/Scripts/setup_firebase_config.sh"
    echo "GOOGLE_REVERSED_CLIENT_ID = ${REVERSED_CLIENT_ID}"
  } > "${XCCONFIG_PATH}"
else
  echo "ERROR: GoogleService-Info.plist not found at ${PLIST_PATH}"
  echo "Set GOOGLE_SERVICE_INFO_PLIST_BASE64 in Codemagic (secure), or add the plist for local builds."
  exit 1
fi
