// Enums matching Android data model exactly

export enum ItemStatus {
  ACTIVE = 'ACTIVE',
  BOUGHT = 'BOUGHT',
}

export enum ItemCategory {
  DAIRY = 'DAIRY',
  VEGETABLES = 'VEGETABLES',
  FRUITS = 'FRUITS',
  MEAT_FISH = 'MEAT_FISH',
  BAKERY = 'BAKERY',
  CLEANING = 'CLEANING',
  PANTRY = 'PANTRY',
  SNACKS = 'SNACKS',
  BEVERAGES = 'BEVERAGES',
  PHARMACY = 'PHARMACY',
  OTHER = 'OTHER',
}

export enum ItemUnit {
  PIECES = 'PIECES',
  KG = 'KG',
  GRAMS = 'GRAMS',
  LITERS = 'LITERS',
  PACKS = 'PACKS',
  BOTTLES = 'BOTTLES',
  BAGS = 'BAGS',
}

export enum MemberRole {
  OWNER = 'OWNER',
  MEMBER = 'MEMBER',
}

export enum ActivityType {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  ITEM_BOUGHT = 'ITEM_BOUGHT',
  ITEM_RESTORED = 'ITEM_RESTORED',
  ITEM_DELETED = 'ITEM_DELETED',
  RECURRING_CREATED = 'RECURRING_CREATED',
  RECURRING_UPDATED = 'RECURRING_UPDATED',
  RECURRING_SUGGESTION_SURFACED = 'RECURRING_SUGGESTION_SURFACED',
  SUGGESTION_ACCEPTED = 'SUGGESTION_ACCEPTED',
}

export enum SuggestionSource {
  FREQUENT = 'FREQUENT',
  RECENT = 'RECENT',
  RECURRING = 'RECURRING',
}

export enum DuplicateReason {
  EXACT_DUPLICATE = 'EXACT_DUPLICATE',
  POSSIBLE_DUPLICATE = 'POSSIBLE_DUPLICATE',
  SIMILAR_ITEM = 'SIMILAR_ITEM',
}
